### ISSUE TITLE
BlazingCache integration

### ISSUE THREAD

**Issue by eolivelli** [sgjava/jcache-tomee#1]
I can provide a PR with integration to BlazingCache.org, which is a recent JSR107 compliant lightweight distributed cache.

Are you interested ?

**Comment by sgjava** [comment]
Go for it.

**Comment by mcRoot** [comment]
Just submitted a PR containing a pom updated with the dependency to the latest released version of Blazing Cache.

**Comment by sgjava** [comment]
I added provider to README.MD and updated to TomEE 7.0.2-SNAPSHOT

**Comment by mcRoot** [comment]
Great! Thanks a lot!

/M
